### ISSUE TITLE
Not able to submit a dummy submission

### ISSUE THREAD

**Issue by asdspal** [ET-BE/myoChallengeEval#1]
Hi, I'm trying to make a dummy submission. I'm getting error `Error : None` for both tasks.
![myo_evalai_submission_error](https://user-images.githubusercontent.com/10200210/184538280-acd5b25b-4b3d-42ec-8984-70b0644d4c5a.png)

**Comment by Vittorio-Caggiano** [comment]
Hi @asdspal , 
thanks for making a submission.
Can I ask a few info to help us troubleshoot?

Did you run and pass all tests with `source setup.sh` ?

Also, did the docker image appear to have been compiled correctly?

May I also ask to pull the latest version of the repo, refresh the auth token (somebody had a [similar issue with the evalAI system](https://bytemeta.vip/repo/facebookresearch/habitat-challenge/issues/110))  and try again?

**Comment by asdspal** [comment]
Thanks for the help. Problem was with the auth-token from eval.ai.  I was able to push images after the refreshing the token.
