### ISSUE TITLE
Missing instructions in README

### ISSUE THREAD

**Issue by pablotano8** [ET-BE/myoChallengeEval#2]
Hi,

On the README file there seems to be missing information under Prerequisites -> Install Docker compiler. The scripts are not shown after this paragraph:
_"Install docker following the [instructions](https://docs.docker.com/get-docker/). Once installed, you can compile the docker containers for the 2 agents with the following scripts:"_

Best,
Pablo

**Comment by Vittorio-Caggiano** [comment]
Hi @pablotanoretamales ,
thanks for catching that! That sentence was not needed there as it referred to the scripts in [STEP 3](https://github.com/ET-BE/myoChallengeEval/blob/main/README.md#step-3-build-a-docker-container-with-the-agent) where dockers is a pre-requisite to compile the container
